repos:
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.5.0-1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.10b0]
        args: ['-l 88']
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.6
      args: ['-l 88']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
