name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone ETA
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel twine
      - name: Install ETA
        run: |
          pip install --no-deps -e .
      - name: Validate version
        run: |
          SETUP_VERSION="$(pip list --format json | jq -r '.[] | select(.name=="voxel51-eta") | .version')"
          TAG_VERSION="$(echo "${{ github.ref }}" | sed 's/^refs\/tags\/v//' | sed 's/-rc\..*//')"
          echo "setup.py version: ${SETUP_VERSION}"
          echo "tagged version: ${TAG_VERSION}"
          test "${SETUP_VERSION}" = "${TAG_VERSION}"
      - name: Build wheel
        run: |
          python setup.py bdist_wheel
      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: dist/*.whl
      - name: Set environment
        env:
          TWINE_USERNAME: __token__
          TWINE_NON_INTERACTIVE: 1
          RELEASE_TAG: ${{ github.ref }}
        run: |
             if [[ $RELEASE_TAG =~ ^refs\/tags\/v.*-rc\.*$ ]]; then
                echo "TWINE_PASSWORD=${{ secrets.FIFTYONE_TEST_PYPI_TOKEN }}" >> $GITHUB_ENV
                echo "TWINE_REPOSITORY_URL=https://test.pypi.org" >> $GITHUB_ENV
             else
                echo "TWINE_PASSWORD=${{ secrets.FIFTYONE_PYPI_TOKEN }}" >> $GITHUB_ENV
                echo "TWINE_REPOSITORY_URL=https://pypi.org" >> $GITHUB_ENV
             fi
      - name: Publish wheel
        run: twine upload dist/*.whl
